version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TARANTOOL_HOST: ${TARANTOOL_HOST}
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
      TARANTOOL_PORT: ${TARANTOOL_PORT}
    depends_on:
      tarantool:
        condition: service_healthy
    networks:
      - app-network

  tarantool:
    container_name: kv-storage-db
    image: tarantool/tarantool:2.11.0
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USER_NAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_USER_PASSWORD}
      TARANTOOL_HOST: ${TARANTOOL_HOST}
      TARANTOOL_PORT: ${TARANTOOL_PORT}
    ports:
      - 3301:3301
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "3301"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge